version: 3
timeout: 5s
dialer_keep_alive: 15s

extra_config:
  github_com/luraproject/lura/router/gin:
    return_error_msg: true
    disable_access_log: false
    disable_redirect_fixed_path: true

endpoints:
  - endpoint: /posts
    method: GET
    output_encoding: no-op
    input_headers:
      - '*'
    input_query_strings:
      - '*'
    backend:
      - host:
          - https://jsonplaceholder.typicode.com
        url_pattern: /posts
        method: GET
        encoding: no-op

  - endpoint: /posts/{id}
    method: GET
    output_encoding: no-op
    input_headers:
      - '*'
    input_query_strings:
      - '*'
    backend:
      - host:
          - https://jsonplaceholder.typicode.com
        url_pattern: /posts/{id}
        method: GET
        encoding: no-op

  - endpoint: /users
    method: GET
    output_encoding: no-op
    input_headers:
      - '*'
    input_query_strings:
      - '*'
    backend:
      - host:
          - https://jsonplaceholder.typicode.com
        url_pattern: /users
        method: GET
        encoding: no-op

  - endpoint: /comments
    method: GET
    output_encoding: no-op
    input_headers:
      - '*'
    input_query_strings:
      - '*'
    backend:
      - host:
          - https://jsonplaceholder.typicode.com
        url_pattern: /comments
        method: GET
        encoding: no-op

  - endpoint: /v1/grpc/empty
    method: POST
    backend:
      - host:
          - grpcb.in:9000
        extra_config:
          plugins/grpc:
            method: grpcbin.GRPCBin/Empty
            descriptor_file: ./proto/grpcb/grpcbin.pb

  - endpoint: /v1/grpc/headers
    method: POST
    backend:
      - host:
          - grpcb.in:9000
        extra_config:
          plugins/grpc:
            method: grpcbin.GRPCBin/HeadersUnary
            descriptor_file: ./proto/grpcb/grpcbin.pb

  - endpoint: /v1/grpc/dummy
    method: POST
    backend:
      - host:
          - grpcb.in:9000
        extra_config:
          plugins/grpc:
            method: grpcbin.GRPCBin/DummyUnary
            descriptor_file: ./proto/grpcb/grpcbin.pb