name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          TAG=${{ github.sha }}
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "Using tag: $TAG"
          docker build --tag $IMAGE_NAME:$TAG \
            .

      - name: Push Docker image
        run: |
          TAG=${{ github.sha }}
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          fi
          docker push $IMAGE_NAME:$TAG
