name: Go CI

on:
  push:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Download dependencies
        run: go mod download
      - name: Formatting check
        run: |
          fmt_issues=$(gofmt -l . | grep -v vendor/ || true)
          if [ -n "$fmt_issues" ]; then
            echo "Formatting issues found:" $fmt_issues
            exit 1
          fi
      - name: Go vet
        run: go vet ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.1
      - name: Test
        run: go test ./... -cover
