name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set image tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> "$GITHUB_ENV"
          else
            echo "IMAGE_TAG=${GITHUB_SHA}" >> "$GITHUB_ENV"
          fi
      - name: Build Docker image
        run: docker build -t api-gateway:${{ env.IMAGE_TAG }} .
